name: client
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  fl_chart: ^0.65.0
  http: ^1.1.2
  email_validator: ^2.0.3
  intl_phone_field: ^3.1.0
  country_code_picker: ^2.0.0
  flutter_bloc: ^8.0.1
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.0
  jwt_decoder: ^2.0.1
  provider: ^6.1.1
  lean_sdk_flutter: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/logo.png
