branch-defaults:
  main:
    environment: hisab-backend-prod-docker
environment-defaults:
  hisab-backend-prod-docker:
    branch: null
    repository: null
global:
  application_name: hisab-backend
  default_ec2_keyname: null
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
